Package = "ble"
InputFiles = [
    "/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h",
    "/System/Library/Frameworks/CoreBluetooth.framework/Headers/CoreBluetooth.h",
    "ble/ble_delegate.h",
]
Classes = [
	"ble_delegate",
	"CBCentralManager",
	"CBPeripheralManager",
	"CBPeripheral",
	"CBCentral",
	"CBService",
	"CBCharacteristic",
	"CBDescriptor",
	"CBError",
	"CBUUID",
	"CBAdvertisementData",
	"CBATTRequest",
	"NSArray",
	"NSMutableArray",
	"NSDictionary",
	"NSEnumerator",
	"NSSet",
	"NSDate",
	"NSTimeZone",
	"NSString",
]
Functions = [
	"NSMakeRange",
]
Enums = [
	"CB.*",
]
Frameworks = [
	"Foundation",
	"CoreBluetooth",
]
Imports = [
	"ble_delegate.h",
]

Pragma = [ 'clang diagnostic ignored "-Wformat-security"' ]
VaArgs = 32
