InputFiles = [
    "/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h",
    "/System/Library/Frameworks/AppKit.framework/Headers/AppKit.h",
]
Classes = [
	"NSArray",
	"NSMutableArray",
	"NSDictionary",
	"NSEnumerator",
	"NSSet",
	"NSDate",
	"NSTimeZone",
	"NSCalendar",
	"NSLocale",
	"NSCharacterSet",
	"NSString",
	"NSScanner",
	"NSFileManager",
	"NSApplication",
	"NSBundle",
	"NSApp",
	"NSWindow",
	"NSScreen",
	"NSEvent",
	"NSResponder",
]
Functions = [
	"NSApplicationMain",
	"NSMake.*",
]
Enums = [
	"CF.*",
	"NSApplication.*",
	"NSBackingStore.*",
	"NSWindowStyleMask.*",
]
Frameworks = [ "Foundation", "AppKit", "CoreGraphics" ]
Pragma = [ 'clang diagnostic ignored "-Wformat-security"' ]
VaArgs = 32
